// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Bi:threeDots': typeof import('~icons/bi/three-dots')['default']
    BiCheck: typeof import('~icons/bi/check')['default']
    BiThreeDots: typeof import('~icons/bi/three-dots')['default']
    BiX: typeof import('~icons/bi/x')['default']
    BookmarksIconFill: typeof import('./components/icons/BookmarksIconFill.vue')['default']
    BookmarksIconOutline: typeof import('./components/icons/BookmarksIconOutline.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    ExploreIconFill: typeof import('./components/icons/ExploreIconFill.vue')['default']
    ExploreIconOutline: typeof import('./components/icons/ExploreIconOutline.vue')['default']
    HomeIconFill: typeof import('./components/icons/HomeIconFill.vue')['default']
    HomeIconOutline: typeof import('./components/icons/HomeIconOutline.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    ListsIconFill: typeof import('./components/icons/ListsIconFill.vue')['default']
    ListsIconOutline: typeof import('./components/icons/ListsIconOutline.vue')['default']
    MessagesIconFill: typeof import('./components/icons/MessagesIconFill.vue')['default']
    MessagesIconOutline: typeof import('./components/icons/MessagesIconOutline.vue')['default']
    MoreIcon: typeof import('./components/icons/MoreIcon.vue')['default']
    Navbar: typeof import('./components/home/Navbar.vue')['default']
    NavItem: typeof import('./components/home/NavItem.vue')['default']
    NotificationsIconFill: typeof import('./components/icons/NotificationsIconFill.vue')['default']
    NotificationsIconOutline: typeof import('./components/icons/NotificationsIconOutline.vue')['default']
    ProfileIconFill: typeof import('./components/icons/ProfileIconFill.vue')['default']
    ProfileIconOutline: typeof import('./components/icons/ProfileIconOutline.vue')['default']
    README: typeof import('./components/README.md')['default']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    Select: typeof import('./components/Select.vue')['default']
    Sidebar: typeof import('./components/home/Sidebar.vue')['default']
    SidebarNav: typeof import('./components/home/SidebarNav.vue')['default']
    Timeline: typeof import('./components/home/Timeline.vue')['default']
    TweetIcon: typeof import('./components/icons/TweetIcon.vue')['default']
    TweetInput: typeof import('./components/home/TweetInput.vue')['default']
    UserDropDown: typeof import('./components/home/UserDropDown.vue')['default']
  }
}

export { }
